spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
app:
  fixed-amount: 4200000
  webhook:
    enabled: true
    url: ${WEBHOOK_URL:http://localhost:9099/payment-callback}
    token-url: https://kc-dev.uz-pay-dev.ox.one/realms/datawise/protocol/openid-connect/token
    client-id: paynet-billing-api
    client-secret: 2wKozwtQAFbTIA9jKMUC6nBKQdO879uR
    connect-timeout: 3s
    read-timeout: 5s
    max-retries: 3
springdoc:
  swagger-ui:
    default-models-expand-depth: -1
    doc-expansion: none
  paths-to-exclude: /api/v1/applications/**
internal:
  api:
    header-name: X-Internal-Key
    key: ${INTERNAL_KEY:7f3d8c4a1b927ed1f6a1f16d7f86dcb9f824ad6}
security:
  creds:
    partners:
      - username: paynet
        password-hash: $2a$10$vQtnAkI3Aj0gEAhj0XFzU./2nX5Fv7SbSXVeiIhAj.K4chF1baOAe
        enabled: true